### ISSUE TITLE
Could not find "juliatopy_ks.jl"

### ISSUE THREAD

**Issue by Neo-101** [maximilian-gelbrecht/NPDEChaos#1]
Dr. Gelbrecht, I recently read your Article "Neural partial differential equations for chaotic systems" published in the New Journal of Physics. 

I found it very interesting and meaningful. 

So I downloaded your code from GitHub, but I encountered a bug when executing NPDEChaos/comparisions/reservoir.py. 

The program cannot find two files: "juliatopy.jl" and "juliatopy_ks.jl", and I searched all your GitHub repositories, but I can't find these two files, and the internet search failed. 

Where can I find these two files?

**Comment by maximilian-gelbrecht** [comment]
Hi!

Thank you for your interest in our work. 

The missing files were just for the comparison to reservoirs, they generate the training data in Julia in a way, so that it is usable for the reservoir code that is written in Python. The reservoir code is in Python (and not in Julia) because it is an old implementation of my co-author. Nonetheless, I also uploaded the missing files now to the GitHub repo.

I’d like to stress that the code is not updated, it is just meant as an archive for the source code of the paper. So by now it features quite old versions of some Julia libraries and uses CuArrays.jl instead of the now recommended CUDA.jl for GPU computations. Send me a mail if you have any other questions about the paper. 

Cheers

**Comment by Neo-101** [comment]
Dr. Gelbrecht, 

Thanks for your quick and patient reply, it helped me a lot.

Cheers
